x_offset: 0
y_offset: 0.06
z_offset: 0.08
roll_offset: -1.999999984507266
pitch_offset: 0
yaw_offset: 0
init_hip_pitch_offset: 0
period_time: 470
dsp_ratio: 0.35
step_forward_back_ratio: 0
foot_height: 0.12
swing_right_left: 0.016
swing_top_down: 0.003
hip_swing_up_amplitude_: 0.4999999961268166
balance_gyro_roll_gain: -0.1
balance_gyro_pitch_gain: -0.02
balance_gyro_y_gain: -0.2
balance_gyro_x_gain: 0.02
