init_x_offset: 0.018
init_y_offset: 0.06
init_z_offset: 0.05
init_roll_offset: 7.999999938029066
init_pitch_offset: 0
init_yaw_offset: 0
init_hip_pitch_offset: 0
period_time: 430
dsp_ratio: 0.1
step_forward_back_ratio: 0
foot_height: 0.08
y_swing_amplitude: 0.016
z_swing_amplitude: 0.004
roll_swing_amplitude: -3.000000083482606
roll_swing_phase: 19.99999941818584
chest_swing_amplitude: 0
shoulder_swing_amplitude: 0
hip_swing_up_amplitude: 1.999999984507266
hip_swing_down_amplitude: -1.999999984507266
balance_gyro_roll_gain: 0
balance_gyro_pitch_gain: 0
balance_gyro_y_gain: 0
balance_gyro_x_gain: 0