
gazebo_dc_motor:
  pid_gains:
    #body
    waist_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    #arm right
    shoulder_r_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    arm_r_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    scissor_rf_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    scissor_rr_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    #arm left
    shoulder_l_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    arm_l_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    scissor_lf_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    scissor_lr_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    #Leg right
    crotch_r_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    thigh_r_01_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    thigh_r_02_joint:
      p: 42.41
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    thigh_r_03_joint:
      p: 42.41
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    toe_r_01_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    toe_r_02_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    #Leg left
    crotch_l_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    thigh_l_01_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    thigh_l_02_joint:
      p: 42.41
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    thigh_l_03_joint:
      p: 42.41
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    toe_l_01_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    toe_l_02_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
