
gazebo_dc_motor:
  motor_characteristics:
    #body
    waist_joint:
      motor_model_type: Voltage
      stall_effort: 3.1
      noload_speed: 6.5
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    #arm right
    shoulder_r_joint:
      motor_model_type: Voltage
      stall_effort: 3.1
      noload_speed: 6.5
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    arm_r_joint:
      motor_model_type: Voltage
      stall_effort: 3.1
      noload_speed: 6.5
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    scissor_rf_joint:
      motor_model_type: Voltage
      stall_effort: 3.1
      noload_speed: 6.5
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    scissor_rr_joint:
      motor_model_type: Voltage
      stall_effort: 3.1
      noload_speed: 6.5
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    #arm left
    shoulder_l_joint:
      motor_model_type: Voltage
      stall_effort: 3.1
      noload_speed: 6.5
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    arm_l_joint:
      motor_model_type: Voltage
      stall_effort: 3.1
      noload_speed: 6.5
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    scissor_lf_joint:
      motor_model_type: Voltage
      stall_effort: 3.1
      noload_speed: 6.5
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    scissor_lr_joint:
      motor_model_type: Voltage
      stall_effort: 3.1
      noload_speed: 6.5
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    #Leg right
    crotch_r_joint:
      motor_model_type: Voltage
      stall_effort: 3.1
      noload_speed: 6.5
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    thigh_r_01_joint:
      motor_model_type: Voltage
      stall_effort: 3.1
      noload_speed: 6.5
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    thigh_r_02_joint:
      motor_model_type: Voltage
      stall_effort: 8.9
      noload_speed: 6.9
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    thigh_r_03_joint:
      motor_model_type: Voltage
      stall_effort: 8.9
      noload_speed: 6.9
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    toe_r_01_joint:
      motor_model_type: Voltage
      stall_effort: 3.1
      noload_speed: 6.5
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    toe_r_02_joint:
      motor_model_type: Voltage
      stall_effort: 3.1
      noload_speed: 6.5
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    #Leg left
    crotch_l_joint:
      motor_model_type: Voltage
      stall_effort: 3.1
      noload_speed: 6.5
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    thigh_l_01_joint:
      motor_model_type: Voltage
      stall_effort: 3.1
      noload_speed: 6.5
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    thigh_l_02_joint:
      motor_model_type: Voltage
      stall_effort: 8.9
      noload_speed: 6.9
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    thigh_l_03_joint:
      motor_model_type: Voltage
      stall_effort: 8.9
      noload_speed: 6.9
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    toe_l_01_joint:
      motor_model_type: Voltage
      stall_effort: 3.1
      noload_speed: 6.5
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    toe_l_02_joint:
      motor_model_type: Voltage
      stall_effort: 3.1
      noload_speed: 6.5
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
