offset:
  waist: 0
  hip_r_roll: 0
  hip_l_roll: 0
  shoulder_r_pitch: 0
  shoulder_l_pitch: 0
  hip_r_pitch: 0
  thigh_r_front_active: 0
  shin_r_active: 0
  ankle_r_roll: 0
  ankle_r_yaw: 0
  hip_l_pitch: 0
  thigh_l_front_active: 0
  shin_l_active: 0
  ankle_l_roll: 0.0
  ankle_l_yaw: 0
  shoulder_r_roll: 0
  elbow_r_rear: 0
  elbow_r_front: 0
  shoulder_l_roll: 0
  elbow_l_rear: 0
  elbow_l_front: 0
