joints:
  ankle_l_roll:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -0.1409236955025448
  ankle_l_yaw:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.0
  ankle_r_roll:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.1409236955025446
  ankle_r_yaw:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.0
  chest:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -3.811648262644352e-21
  elbow_l_front:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 1.4210854715202004e-14
  elbow_l_rear:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -1.4210854715202004e-14
  elbow_r_front:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -2.007128639793494
  elbow_r_rear:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 2.007128639793494
  hip_l_pitch:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.0
  hip_l_roll:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -0.1409236955025448
  hip_r_pitch:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.0
  hip_r_roll:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -0.1409236955025446
  shin_l_active:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.2628263565708387
  shin_r_active:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -0.2628263565708385
  shoulder_l_pitch:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 1.5707963267948888
  shoulder_l_roll:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -9.769962616701378e-15
  shoulder_r_pitch:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 1.134464013796322
  shoulder_r_roll:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 1.43116998663536
  thigh_l_active:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -0.03884820997690153
  thigh_r_active:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.03884820997690064
speed_scale:
  ankle_l_roll: 1.0
  ankle_l_yaw: 1.0
  ankle_r_roll: 1.0
  ankle_r_yaw: 1.0
  chest: 1.0
  elbow_l_front: 1.0
  elbow_l_rear: 1.0
  elbow_r_front: 1.0
  elbow_r_rear: 1.0
  hip_l_pitch: 1.0
  hip_l_roll: 1.0
  hip_r_pitch: 1.0
  hip_r_roll: 1.0
  shin_l_active: 1.0
  shin_r_active: 1.0
  shoulder_l_pitch: 1.0
  shoulder_l_roll: 1.0
  shoulder_r_pitch: 1.0
  shoulder_r_roll: 1.0
  thigh_l_active: 1.0
  thigh_r_active: 1.0
time:
  move_duration: 0.2
  wait_duration: 0.0
