gazebo_dc_motor:
  pid_gains:
    #body
    waist_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    #arm right
    shoulder_r_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    arm_r_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    scissor_rf_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    scissor_rr_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    #arm left
    shoulder_l_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    arm_l_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    scissor_lf_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    scissor_lr_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    #Leg right
    hip_r_roll_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    hip_r_pitch_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    thigh_r_active_joint:
      p: 42.41
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    shin_r_active_joint:
      p: 42.41
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    ankle_r_roll_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    ankle_r_yaw_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    #Leg left
    hip_l_roll_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    hip_l_pitch_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    thigh_l_active_joint:
      p: 42.41
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    shin_l_active_joint:
      p: 42.41
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    ankle_l_roll_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    ankle_l_yaw_joint:
      p: 16.62
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
