# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 1000

# Position Controllers ---------------------------------------
waist_joint_position:
  type: position_controllers/JointPositionController
  joint: waist_joint

shoulder_r_pitch_joint_position:
  type: position_controllers/JointPositionController
  joint: shoulder_r_pitch_joint
shoulder_r_roll_joint_position:
  type: position_controllers/JointPositionController
  joint: shoulder_r_roll_joint
elbow_r_front_joint_position:
  type: position_controllers/JointPositionController
  joint: elbow_r_front_joint
elbow_r_rear_joint_position:
  type: position_controllers/JointPositionController
  joint: elbow_r_rear_joint

shoulder_l_pitch_joint_position:
  type: position_controllers/JointPositionController
  joint: shoulder_l_pitch_joint
shoulder_l_roll_joint_position:
  type: position_controllers/JointPositionController
  joint: shoulder_l_roll_joint
elbow_l_front_joint_position:
  type: position_controllers/JointPositionController
  joint: elbow_l_front_joint
elbow_l_rear_joint_position:
  type: position_controllers/JointPositionController
  joint: elbow_l_rear_joint

hip_r_roll_joint_position:
  type: position_controllers/JointPositionController
  joint: hip_r_roll_joint
hip_r_pitch_joint_position:
  type: position_controllers/JointPositionController
  joint: hip_r_pitch_joint
thigh_r_front_active_joint_position:
  type: position_controllers/JointPositionController
  joint: thigh_r_front_active_joint
shin_r_active_joint_position:
  type: position_controllers/JointPositionController
  joint: shin_r_active_joint
ankle_r_roll_joint_position:
  type: position_controllers/JointPositionController
  joint: ankle_r_roll_joint
ankle_r_yaw_joint_position:
  type: position_controllers/JointPositionController
  joint: ankle_r_yaw_joint

hip_l_roll_joint_position:
  type: position_controllers/JointPositionController
  joint: hip_l_roll_joint
hip_l_pitch_joint_position:
  type: position_controllers/JointPositionController
  joint: hip_l_pitch_joint
thigh_l_front_active_joint_position:
  type: position_controllers/JointPositionController
  joint: thigh_l_front_active_joint
shin_l_active_joint_position:
  type: position_controllers/JointPositionController
  joint: shin_l_active_joint
ankle_l_roll_joint_position:
  type: position_controllers/JointPositionController
  joint: ankle_l_roll_joint
ankle_l_yaw_joint_position:
  type: position_controllers/JointPositionController
  joint: ankle_l_yaw_joint
