joints:
  ankle_l_roll:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -0.1413716694115407
  ankle_l_yaw:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.0
  ankle_r_roll:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.1413716694115407
  ankle_r_yaw:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.0
  chest:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -1.0471975511965976
  elbow_l_front:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 1.5707963267948966
  elbow_l_rear:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -1.5707963267948966
  elbow_r_front:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -1.5707963267948966
  elbow_r_rear:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 1.5707963267948966
  hip_l_pitch:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.0
  hip_l_roll:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -0.1413716694115407
  hip_r_pitch:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.0
  hip_r_roll:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -0.1413716694115407
  shin_l_rear:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.26354471705114374
  shin_r_rear:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -0.26354471705114374
  shoulder_l_pitch:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.8726646259971648
  shoulder_l_roll:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -1.5707963267948966
  shoulder_r_pitch:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 1.5707963267948966
  shoulder_r_roll:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 1.5707963267948966
  knee_l_rear:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -0.038397243543875255
  knee_r_rear:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.038397243543875255
speed_scale:
  ankle_l_roll: 1.0
  ankle_l_yaw: 1.0
  ankle_r_roll: 1.0
  ankle_r_yaw: 1.0
  chest: 1.0
  elbow_l_front: 1.0
  elbow_l_rear: 1.0
  elbow_r_front: 1.0
  elbow_r_rear: 1.0
  hip_l_pitch: 1.0
  hip_l_roll: 1.0
  hip_r_pitch: 1.0
  hip_r_roll: 1.0
  shin_l_rear: 1.0
  shin_r_rear: 1.0
  shoulder_l_pitch: 1.0
  shoulder_l_roll: 1.0
  shoulder_r_pitch: 1.0
  shoulder_r_roll: 1.0
  knee_l_rear: 1.0
  knee_r_rear: 1.0
time:
  move_duration: 0.2
  wait_duration: 0.0
