# 1.0 -> 1 [deg]

ankle_r_yaw_gain: 0.0
hip_r_roll_gain: 0.0
hip_r_pitch_gain: 0.0
knee_r_rear_gain: 0.0
shin_r_rear_gain: 0.0
ankle_r_roll_gain: 0.0

ankle_l_yaw_gain: 0.0
hip_l_roll_gain: 0.0
hip_l_pitch_gain: 0.0
knee_l_rear_gain: 0.0
shin_l_rear_gain: 0.0
ankle_l_roll_gain: 0.0
