ankle_r_yaw_p_gain: 0.0
ankle_r_yaw_d_gain: 0.0

hip_r_roll_p_gain: 0.0
hip_r_roll_d_gain: 0.0

hip_r_pitch_p_gain: 0.0
hip_r_pitch_d_gain: 0.0

knee_r_rear_p_gain: 0.0
knee_r_rear_d_gain: 0.0

shin_r_rear_p_gain: 0.0
shin_r_rear_d_gain: 0.0

ankle_r_roll_p_gain: 0.0
ankle_r_roll_d_gain: 0.0

ankle_l_yaw_p_gain: 0.0
ankle_l_yaw_d_gain: 0.0

hip_l_roll_p_gain: 0.0
hip_l_roll_d_gain: 0.0

hip_l_pitch_p_gain: 0.0
hip_l_pitch_d_gain: 0.0

knee_l_rear_p_gain: 0.0
knee_l_rear_d_gain: 0.0

shin_l_rear_p_gain: 0.0
shin_l_rear_d_gain: 0.0

ankle_l_roll_p_gain: 0.0
ankle_l_roll_d_gain: 0.0
