<package format="2">
  <name>kuroko_optimization</name>
  <version>0.1.0</version>
  <description>Preview control optimization using Scilab</description>

  <maintainer email="you@example.com">Your Name</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>roscpp</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>robotis_math</build_depend>
  <build_depend>scilab_optimization</build_depend>
  <build_depend>kuroko_online_walking_module_msgs</build_depend>

  <exec_depend>roscpp</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>robotis_math</exec_depend>
  <exec_depend>scilab_optimization</exec_depend>
  <exec_depend>kuroko_online_walking_module_msgs</exec_depend>

</package>
