joints:
  ankle_l_roll:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -0.1409236955025448
  ankle_l_yaw:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -0.017453292519943295
  ankle_r_roll:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.1409236955025446
  ankle_r_yaw:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.017453292519943295
  chest:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 1.0471975511965976
  elbow_l_front:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 2.007128639793493
  elbow_l_rear:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -2.007128639793493
  elbow_r_front:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -2.007128639793494
  elbow_r_rear:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -2.007128639793464
  hip_l_pitch:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -0.17453292519943295
  hip_l_roll:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -0.053657232902828325
  hip_r_pitch:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.17453292519943295
  hip_r_roll:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -0.22819015810226106
  shin_l_active:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.4373592817702716
  shin_r_active:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -0.48971915933010135
  shoulder_l_pitch:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -1.134464013796322
  shoulder_l_roll:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -1.43116998663536
  shoulder_r_pitch:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 7.771561172376096e-15
  shoulder_r_roll:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -0.26179938779913964
  thigh_l_active:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.030964960102871652
  thigh_r_active:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -0.03096496010287254
speed_scale:
  ankle_l_roll: 1.0
  ankle_l_yaw: 1.0
  ankle_r_roll: 1.0
  ankle_r_yaw: 1.0
  chest: 1.0
  elbow_l_front: 1.0
  elbow_l_rear: 1.0
  elbow_r_front: 1.0
  elbow_r_rear: 1.0
  hip_l_pitch: 1.0
  hip_l_roll: 1.0
  hip_r_pitch: 1.0
  hip_r_roll: 1.0
  shin_l_active: 1.0
  shin_r_active: 1.0
  shoulder_l_pitch: 1.0
  shoulder_l_roll: 1.0
  shoulder_r_pitch: 1.0
  shoulder_r_roll: 1.0
  thigh_l_active: 1.0
  thigh_r_active: 1.0
time:
  move_duration: 0.15
  wait_duration: 0.0
