layout:
  arrow:
    arrow_0:
      info:
        id: 0
      waypoints: []
    arrow_1:
      info:
        id: 1
      waypoints: []
    arrow_10:
      info:
        id: 10
      waypoints: []
    arrow_2:
      info:
        id: 2
      waypoints: []
    arrow_3:
      info:
        id: 3
      waypoints: []
    arrow_4:
      info:
        id: 4
      waypoints: []
    arrow_5:
      info:
        id: 5
      waypoints: []
    arrow_6:
      info:
        id: 6
      waypoints: []
    arrow_7:
      info:
        id: 7
      waypoints: []
    arrow_8:
      info:
        id: 8
      waypoints: []
    arrow_9:
      info:
        id: 9
      waypoints: []
  block:
    frame_0_pose_01:
      connection:
        output:
          out_0:
            arrow: arrow_1
            ch: 0
            target: frame_2_pose_02
      info:
        filename: pose_01
        id: 0
        type: frame
      place:
        x: 562.0
        y: 605.0
    frame_10_posr_10:
      connection:
        output:
          out_0:
            arrow: arrow_9
            ch: 0
            target: frame_11_posr_11
      info:
        filename: posr_10
        id: 10
        type: frame
      place:
        x: 585.0
        y: 1523.0
    frame_11_posr_11:
      connection:
        output:
          out_0:
            arrow: arrow_10
            ch: 0
            target: frame_8_pose_08
      info:
        filename: posr_11
        id: 11
        type: frame
      place:
        x: 589.0
        y: 1637.0
    frame_2_pose_02:
      connection:
        output:
          out_0:
            arrow: arrow_8
            ch: 0
            target: frame_3_pose_03
      info:
        filename: pose_02
        id: 2
        type: frame
      place:
        x: 567.0
        y: 709.0
    frame_3_pose_03:
      connection:
        output:
          out_0:
            arrow: arrow_3
            ch: 0
            target: frame_4_pose_04
      info:
        filename: pose_03
        id: 3
        type: frame
      place:
        x: 557.0
        y: 815.0
    frame_4_pose_04:
      connection:
        output:
          out_0:
            arrow: arrow_4
            ch: 0
            target: frame_5_pose_05
      info:
        filename: pose_04
        id: 4
        type: frame
      place:
        x: 567.0
        y: 937.0
    frame_5_pose_05:
      connection:
        output:
          out_0:
            arrow: arrow_5
            ch: 0
            target: frame_6_pose_06
      info:
        filename: pose_05
        id: 5
        type: frame
      place:
        x: 573.0
        y: 1046.0
    frame_6_pose_06:
      connection:
        output:
          out_0:
            arrow: arrow_6
            ch: 0
            target: frame_7_pose_07
      info:
        filename: pose_06
        id: 6
        type: frame
      place:
        x: 573.0
        y: 1173.0
    frame_7_pose_07:
      connection:
        output:
          out_0:
            arrow: arrow_7
            ch: 0
            target: frame_9_pose_09
      info:
        filename: pose_07
        id: 7
        type: frame
      place:
        x: 576.0
        y: 1289.0
    frame_8_pose_08:
      connection:
        output:
          out_0:
            ch: 0
      info:
        filename: pose_08
        id: 8
        type: frame
      place:
        x: 598.0
        y: 1744.0
    frame_9_pose_09:
      connection:
        output:
          out_0:
            arrow: arrow_2
            ch: 0
            target: frame_10_posr_10
      info:
        filename: pose_09
        id: 9
        type: frame
      place:
        x: 591.0
        y: 1402.0
    start_1:
      connection:
        output:
          out_0:
            arrow: arrow_0
            ch: 0
            target: frame_0_pose_01
      info:
        filename: ''
        id: 1
        type: start
      place:
        x: 642.0
        y: 487.0
