joint_names:
  [
    waist_joint,
    shoulder_r_pitch_joint,
    shoulder_r_roll_joint,
    elbow_r_front_joint,
    elbow_r_rear_joint,
    shoulder_l_pitch_joint,
    shoulder_l_roll_joint,
    elbow_l_front_joint,
    elbow_l_rear_joint,
    hip_r_roll_joint,
    hip_r_pitch_joint,
    thigh_r_front_active_joint,
    shin_r_active_joint,
    ankle_r_roll_joint,
    ankle_r_yaw_joint,
    hip_l_roll_joint,
    hip_l_pitch_joint,
    thigh_l_front_active_joint,
    shin_l_active_joint,
    ankle_l_roll_joint,
    ankle_l_yaw_joint,
  ]

positions:
  [
    0,
    0.94,
    0.4,
    -2.4,
    -1.1,
    -0.94,
    -0.4,
    2.4,
    1.1,
    0,
    -0.01,
    0,
    -0.1,
    0,
    0,
    0,
    0.01,
    0,
    0.1,
    0,
    0,
  ]
