joints:
  ankle_l_roll:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -0.1409236955025448
  ankle_l_yaw:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.0
  ankle_r_roll:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.1409236955025446
  ankle_r_yaw:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.0
  chest:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 1.0471975511965976
  elbow_l_front:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 2.007128639793493
  elbow_l_rear:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -2.007128639793493
  elbow_r_front:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.5235987755982837
  elbow_r_rear:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -0.5235987755982837
  hip_l_pitch:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.0
  hip_l_roll:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -0.1409236955025448
  hip_r_pitch:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.0
  hip_r_roll:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -0.1409236955025446
  shin_l_active:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.47226586681015825
  shin_r_active:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -0.4722658668101581
  shoulder_l_pitch:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -1.134464013796322
  shoulder_l_roll:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -1.43116998663536
  shoulder_r_pitch:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 7.771561172376096e-15
  shoulder_r_roll:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 9.769962616701378e-15
  thigh_l_active:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: 0.11823142270258813
  thigh_r_active:
    enable: true
    feedback: ''
    pid:
    - 0.0
    - 0.0
    - 0.0
    position: -0.11823142270258902
speed_scale:
  ankle_l_roll: 1.0
  ankle_l_yaw: 1.0
  ankle_r_roll: 1.0
  ankle_r_yaw: 1.0
  chest: 1.0
  elbow_l_front: 1.0
  elbow_l_rear: 1.0
  elbow_r_front: 1.0
  elbow_r_rear: 1.0
  hip_l_pitch: 1.0
  hip_l_roll: 1.0
  hip_r_pitch: 1.0
  hip_r_roll: 1.0
  shin_l_active: 1.0
  shin_r_active: 1.0
  shoulder_l_pitch: 1.0
  shoulder_l_roll: 1.0
  shoulder_r_pitch: 1.0
  shoulder_r_roll: 1.0
  thigh_l_active: 1.0
  thigh_r_active: 1.0
time:
  move_duration: 0.1
  wait_duration: 0.0
