### Footstep parameterization for KUROKO #########

### footstep settings #########################################################
# Footstep displacement vectors (in meter / rad)
# WARNING: data type has to be float since integers will cause an exception
footsteps:
  x:
    [
      0.0,
      0.068,
      -0.034,
      0.0,
      0.0425,
      0.0085,
      0.01275,
      0.034,
      -0.0255,
      0.051,
      0.034,
      -0.017,
    ]
  y:
    [
      0.136,
      0.0915,
      0.0915,
      0.102,
      0.119,
      0.1105,
      0.095,
      0.102,
      0.102,
      0.102,
      0.095,
      0.102,
    ]
  theta: [0.0, 0.0, 0.0, 0.0, 0.0, -0.425, 0.425, 0.255, 0.425, 0.0, 0.0, 0.0]

### foot settings #############################################################
foot:
  size: { x: 0.12, y: 0.075, z: 0.008 }
  separation: 0.07
  origin_shift: { x: 0.0, y: 0 }
  max:
    step: { x: 0.04, y: 0.04, theta: 0.3 }
    inverse:
      step: { x: -0.04, y: 0.04, theta: -0.3 }

### step range ################################################################

# more accurate than the bounding box defined by the max/max inverse step
step_range:
  x:
    [
      0.0,
      0.0085,
      0.017,
      0.0255,
      0.0425,
      0.051,
      0.0595,
      0.0595,
      -0.0255,
      -0.0255,
      -0.017,
      -0.0085,
    ]
  y:
    [
      0.1275,
      0.1275,
      0.1275,
      0.119,
      0.1105,
      0.1105,
      0.102,
      0.0915,
      0.0915,
      0.1105,
      0.119,
      0.1275,
    ]
