<?xml version="1.0"?>
<package format="2">
  <name>kuroko_module_loader</name>
  <version>0.0.0</version>
  <description> The kuroko_balance_control package </description>
  <author>nyxrobotics</author>
  <author email="nyxroboticss@gmail.com">nyxrobotics</author>
  <maintainer email="nyxroboticss@gmail.com">nyxrobotics</maintainer>
  <license>Apache 2.0</license>
  <url type="website">https://github.com/nyxrobotics</url>
  <url type="repository">https://github.com/nyxrobotics/kuroko_ros</url>
  <url type="bugtracker">https://github.com/nyxrobotics/kuroko_ros/issues</url>
  <buildtool_depend>catkin</buildtool_depend>
  <depend>roscpp</depend>
  <depend>robotis_controller_msgs</depend>
  <depend>kuroko_action_module_msgs</depend>
  <depend>op3_walking_module_msgs</depend>
  <depend>op3_online_walking_module_msgs</depend>
  <depend>cmake_modules</depend>
  <depend>dynamixel_sdk</depend>
  <depend>robotis_framework_common</depend>
  <depend>robotis_device</depend>
  <depend>kuroko_joint_controller</depend>
  <depend>robotis_math</depend>
  <depend>kuroko_kinematics</depend>
  <depend>kuroko_balance_control</depend>
  <depend>open_cr_module</depend>
  <depend>kuroko_initial_pose_module</depend>
  <depend>kuroko_head_control_module</depend>
  <depend>kuroko_walking_module</depend>
  <depend>kuroko_action_module</depend>
  <depend>kuroko_direct_control_module</depend>
  <depend>kuroko_online_walking_module</depend>
  <depend>kuroko_tuning_module</depend>
  <depend>op3_tuning_module_msgs</depend>
  <exec_depend>kuroko_localization</exec_depend>
</package>
