joints:
  ankle_l_roll:
    enable: true
    position: -0.1413716694115407
  ankle_l_yaw:
    enable: true
    position: 0.0
  ankle_r_roll:
    enable: true
    position: 0.1413716694115407
  ankle_r_yaw:
    enable: true
    position: 0.0
  chest:
    enable: true
    position: -0.0
  elbow_l_front:
    enable: true
    position: 2.007128639793479
  elbow_l_rear:
    enable: true
    position: -2.007128639793479
  elbow_r_front:
    enable: true
    position: -2.007128639793479
  elbow_r_rear:
    enable: true
    position: 2.007128639793479
  hip_l_pitch:
    enable: true
    position: 0.0
  hip_l_roll:
    enable: true
    position: -0.1413716694115407
  hip_r_pitch:
    enable: true
    position: 0.0
  hip_r_roll:
    enable: true
    position: -0.1413716694115407
  shin_l_active:
    enable: true
    position: 0.26354471705114374
  shin_r_active:
    enable: true
    position: -0.26354471705114374
  shoulder_l_pitch:
    enable: true
    position: -1.1344640137963142
  shoulder_l_roll:
    enable: true
    position: -1.4311699866353502
  shoulder_r_pitch:
    enable: true
    position: 1.1344640137963142
  shoulder_r_roll:
    enable: true
    position: 1.4311699866353502
  thigh_l_active:
    enable: true
    position: -0.038397243543875255
  thigh_r_active:
    enable: true
    position: 0.038397243543875255
