motion:
  -2: BRAKE
  -1: STOP
  0: GetupFront
  1: GetupRear
  2: CrouchDown
  3: CrouchUp
  # Attack
  4: LGripFront
  5: LHookFront
  6: LPunchHigh
  7: LPunchLow
  8: RGripFront
  9: RHookFront
  10: RPunchHigh
  11: RPunchLow
motion_shortcut:
# motion_index : button id (0 ~ 9)
