id_joint:
  1: shoulder_r_pitch
  2: shoulder_l_pitch
  3: shoulder_r_roll
  4: shoulder_l_roll
  5: elbow_r_front
  6: elbow_l_front
  7: ankle_r_yaw
  8: ankle_l_yaw
  9: hip_r_roll
  10: hip_l_roll
  11: hip_r_pitch
  12: hip_l_pitch
  13: thigh_r_front_active
  14: thigh_l_front_active
  15: shin_r_active
  16: shin_l_active
  17: ankle_r_roll
  18: ankle_l_roll
module_list:
  [
    none,
    head_control_module,
    initial_pose_module,
    walking_module,
    manipulation_module,
    action_module,
    walking_module,
    direct_control_module,
    online_walking_module,
  ]
module_button:
  1: none
  2: head_control_module
  3: action_module
  4: walking_module
  5: online_walking_module
  6: direct_control_module
