motion:
  -2: BRAKE
  -1: STOP
  0: CrouchDown
  1: CrouchUp
  2: GetupFront
  3: GetupRear
  # Attack
  4: LGripFront
  5: LHookFront
  6: LPunchHigh
  7: LPunchLow
  8: RGripFront
  9: RHookFront
  10: RPunchHigh
  11: RPunchLow
motion_shortcut:
# motion_index : button id (0 ~ 9)
